.TH capit 1 15-JUL-2021 "Kozmix Go"

.SH NAME
capit \- capitalise from stdin to stdout

.SH SYNOPSIS
capit [-L lang]

.SH DESCRIPTION
.B capit
reads lines from stdin and outputs them capitalised to stdout.

There is one optional option:

.TP
.B \-L lang
use capitalisation rules for language "lang" (defaults to English)


.SH SEE ALSO
.BR manglename (1)

.SH BUGS
Surely none.

.SH AUTHOR
svm
