.TH capit 1 27-JUN-2022 "Kozmix Go"

.SH NAME
capit \- capitalise from stdin to stdout

.SH SYNOPSIS
.B capit
[\-u \-l \-c ] [-L lang]

.SH DESCRIPTION
.B capit
reads lines from stdin and outputs them to stdout with capitalisation
changed as follows:

.TP
.B \-u
change all characters to uppercase
.TP
.B \-l
change all characters to lowercase
.TP
.B \-c
capitalise all words (the default)

.P
There is one additional optional option:

.TP
.B \-L lang
use capitalisation rules for language "lang" (defaults to English)


.SH SEE ALSO
.BR manglename (1)

.SH BUGS
Surely none.

.SH AUTHOR
svm
